package reporting

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/ubank/vuln-platform/internal/domain/entity"
	"github.com/ubank/vuln-platform/internal/domain/repository"
)

// Generator ties together data fetch (via existing repository ports
// — no bespoke queries), rendering (Table -> CSV/XLSX/PDF), and
// persistence (bytes to disk, metadata to Postgres via
// ReportRepository).
type Generator struct {
	findings    repository.FindingRepository
	hosts       repository.HostRepository
	remediation repository.RemediationRepository
	patchJobs   repository.PatchJobRepository
	audit       repository.AuditRepository
	reports     repository.ReportRepository
	stats       *StatsCollector
	storageDir  string
}

func NewGenerator(
	findings repository.FindingRepository,
	hosts repository.HostRepository,
	remediation repository.RemediationRepository,
	patchJobs repository.PatchJobRepository,
	audit repository.AuditRepository,
	reports repository.ReportRepository,
	storageDir string,
) *Generator {
	return &Generator{
		findings:    findings,
		hosts:       hosts,
		remediation: remediation,
		patchJobs:   patchJobs,
		audit:       audit,
		reports:     reports,
		stats:       NewStatsCollector(findings, hosts, remediation),
		storageDir:  storageDir,
	}
}

// maxRows caps how many records a single report pulls in this
// scaffold's page-through-everything approach (see stats.go's doc
// comment on the same limitation). Raise this, or better, replace
// with streaming/cursor-based export, before running this against the
// full 100k+ finding scale in one report.
const maxRows = 5000

// Generate builds the requested report, writes it to storageDir, and
// records its metadata. Returns the generated bytes as well so the
// HTTP handler can serve them directly without a second disk read.
func (g *Generator) Generate(ctx context.Context, reportType entity.ReportType, format entity.ReportFormat, generatedBy string) (*entity.Report, []byte, error) {
	table, isSummary, summaryStats, err := g.buildData(ctx, reportType)
	if err != nil {
		return nil, nil, fmt.Errorf("fetch data for %s report: %w", reportType, err)
	}

	var data []byte
	switch format {
	case entity.ReportFormatCSV:
		if isSummary {
			return nil, nil, fmt.Errorf("executive_summary is not available in CSV format; use pdf")
		}
		data, err = WriteCSV(table)
	case entity.ReportFormatXLSX:
		if isSummary {
			return nil, nil, fmt.Errorf("executive_summary is not available in xlsx format; use pdf")
		}
		data, err = WriteXLSX(table)
	case entity.ReportFormatPDF:
		if isSummary {
			data, err = WriteExecutiveSummaryPDF(summaryStats)
		} else {
			data, err = WriteTablePDF(table)
		}
	default:
		return nil, nil, fmt.Errorf("unsupported report format %q", format)
	}
	if err != nil {
		return nil, nil, fmt.Errorf("render %s report as %s: %w", reportType, format, err)
	}

	if err := os.MkdirAll(g.storageDir, 0o750); err != nil {
		return nil, nil, fmt.Errorf("prepare report storage directory: %w", err)
	}
	filename := fmt.Sprintf("%s-%d.%s", reportType, time.Now().Unix(), format)
	storagePath := filepath.Join(g.storageDir, filename)
	if err := os.WriteFile(storagePath, data, 0o640); err != nil {
		return nil, nil, fmt.Errorf("write report file: %w", err)
	}

	report := &entity.Report{
		ReportType:  reportType,
		Format:      format,
		StoragePath: storagePath,
		GeneratedBy: generatedBy,
	}
	if err := g.reports.Create(ctx, report); err != nil {
		return nil, nil, fmt.Errorf("record report metadata: %w", err)
	}

	return report, data, nil
}

func (g *Generator) buildData(ctx context.Context, reportType entity.ReportType) (Table, bool, *ExecutiveSummaryStats, error) {
	switch reportType {
	case entity.ReportExecutiveSummary:
		stats, err := g.stats.ExecutiveSummary(ctx)
		return Table{}, true, stats, err

	case entity.ReportTechnical, entity.ReportPackage, entity.ReportCVE, entity.ReportRHSA:
		// All four pull from the same findings dataset; Package/CVE/
		// RHSA-specific filtering happens via FindingFilter before
		// calling Generate in a future refinement (e.g. a report
		// scoped to one RHSA) — for now these render the same
		// technical findings table, which already includes the
		// extracted CVE/RHSA/package columns.
		findings, _, err := g.findings.List(ctx, repository.FindingFilter{Page: 1, PageSize: maxRows})
		return FindingsTable(findings), false, nil, err

	case entity.ReportHost:
		hosts, _, err := g.hosts.List(ctx, repository.HostFilter{Page: 1, PageSize: maxRows})
		return HostsTable(hosts), false, nil, err

	case entity.ReportVerification:
		tasks, _, err := g.remediation.List(ctx, repository.RemediationFilter{Page: 1, PageSize: maxRows})
		return RemediationTable(tasks), false, nil, err

	case entity.ReportPatch:
		// Patch jobs are per-task; a fleet-wide patch report pages
		// through remediation tasks and fetches their job history.
		// Bounded by maxRows on the task side already.
		tasks, _, err := g.remediation.List(ctx, repository.RemediationFilter{Page: 1, PageSize: maxRows})
		if err != nil {
			return Table{}, false, nil, err
		}
		var allJobs []*entity.PatchJob
		for _, task := range tasks {
			jobs, err := g.patchJobs.ListByTask(ctx, task.ID)
			if err != nil {
				return Table{}, false, nil, fmt.Errorf("list patch jobs for task %s: %w", task.ID, err)
			}
			allJobs = append(allJobs, jobs...)
		}
		return PatchJobsTable(allJobs), false, nil, nil

	case entity.ReportAudit:
		logs, _, err := g.audit.Query(ctx, repository.AuditFilter{Page: 1, PageSize: maxRows})
		return AuditTable(logs), false, nil, err

	default:
		return Table{}, false, nil, fmt.Errorf("unknown report type %q", reportType)
	}
}
