apiVersion: v2
name: vuln-platform
description: Enterprise Vulnerability Management Platform for RHEL/OpenShift fleets
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - vulnerability-management
  - rhel
  - openshift
  - security
maintainers:
  - name: Platform Engineering
