apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vuln-platform.fullname" . }}-config
  labels:
    {{- include "vuln-platform.labels" . | nindent 4 }}
data:
  VULN_ENV: {{ .Values.config.env | quote }}
  VULN_HTTP_PORT: {{ .Values.config.httpPort | quote }}
  VULN_DATABASE_HOST: {{ .Values.config.database.host | quote }}
  VULN_DATABASE_PORT: {{ .Values.config.database.port | quote }}
  VULN_DATABASE_NAME: {{ .Values.config.database.name | quote }}
  VULN_DATABASE_USER: {{ .Values.config.database.user | quote }}
  VULN_DATABASE_SSL_MODE: {{ .Values.config.database.sslMode | quote }}
  VULN_DATABASE_MAX_CONNS: {{ .Values.config.database.maxConns | quote }}
  VULN_DATABASE_MIN_CONNS: {{ .Values.config.database.minConns | quote }}
  VULN_REDIS_ADDR: {{ .Values.config.redis.addr | quote }}
  VULN_SSH_STRICT_HOST_KEY_CHECK: {{ .Values.config.ssh.strictHostKeyCheck | quote }}
  VULN_SSH_MAX_CONCURRENT: {{ .Values.config.ssh.maxConcurrent | quote }}
  VULN_SSH_MAX_RETRIES: {{ .Values.config.ssh.maxRetries | quote }}
  VULN_IMPORT_WORKER_CONCURRENCY: {{ .Values.config.importer.workerConcurrency | quote }}
  VULN_IMPORT_QUEUE_DEPTH: {{ .Values.config.importer.queueDepth | quote }}
  VULN_IMPORT_MAX_FILE_SIZE_MB: {{ .Values.config.importer.maxFileSizeMB | quote }}
  VULN_SAFETY_ALLOW_FULL_SYSTEM_UPDATE: {{ .Values.config.safety.allowFullSystemUpdate | quote }}
  VULN_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
